# Site settings
title: Fracktal Blog
email: support@fracktal.in
description: > # this means to ignore newlines until "baseurl:"
  We aim to create a system where we can emphasize the most fundamental of all human traits- Creation!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fracktal.in" # the base hostname & protocol for your site
twitter_username: fracktalworks
github_username:  fracktalworks

# Build settings
markdown: kramdown
